[package]
name = "bird-detection"
version = "0.1.0"
edition = "2024"

[features]
default = []
cuda = ["ort/cuda"]
load-dynamic = ["ort/load-dynamic"]  # Optional: for users who want runtime loading

[dependencies]
# Machine Learning
birdnet-onnx = { version = "=2.0.0-rc.13" }
ort = { version = "2.0.0-rc.11", features = ["download-binaries", "tracing", "ndarray"] }

# Audio
cpal = "0.17.3"
# Ringbuffer
ringbuf = "0.4"

# asyn runtime
smol = "2.0.2"
smol-macros = "0.1.1"

#logging
env_logger = "0.11.10"
log = "0.4.29"
# macros for better error handlng
thiserror = "2"
image = "0.25.10"
base64 = "0.22.1"
